server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/peraxis_main
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:peraxis123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET:peraxis-jwt-secret-key-2024-super-secure-minimum-256-bits}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info