server:
  port: 8086

spring:
  application:
    name: payment-service

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
    secret: ${RAZORPAY_KEY_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info