server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000,http://localhost:3001,http://localhost:3002"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: ai-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/ai/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/payments/**
        - id: admin-service-direct
          uri: http://localhost:8085
          predicates:
            - Path=/api/admin/**
        - id: admin-service
          uri: http://localhost:8085
          predicates:
            - Path=/admin-service/api/admin/**
          filters:
            - RewritePath=/admin-service/api/admin/(?<segment>.*), /api/admin/$\{segment}
        - id: activity-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/activity/**
        - id: search-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/search/**
        - id: notification-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/notifications/**
        - id: websocket-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/websocket/**
        - id: websocket-connection
          uri: ws://localhost:8087
          predicates:
            - Path=/ws/**
        - id: admin-websocket
          uri: ws://localhost:8085
          predicates:
            - Path=/admin-service/ws/admin/**
          filters:
            - RewritePath=/admin-service/ws/admin/(?<segment>.*), /ws/admin/$\{segment}
        - id: admin-websocket-direct
          uri: ws://localhost:8085
          predicates:
            - Path=/ws/admin/**
        - id: location-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/location/**



jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics