server:
  port: 8088

spring:
  application:
    name: notification-service
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:}
  auth:
    token: ${TWILIO_AUTH_TOKEN:}
  phone:
    number: ${TWILIO_PHONE_NUMBER:}

management:
  endpoints:
    web:
      exposure:
        include: health,info