server:
  port: 8090

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/peraxis_activities

management:
  endpoints:
    web:
      exposure:
        include: health,info