global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:8085']
    metrics_path: '/actuator/prometheus'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8086']
    metrics_path: '/actuator/prometheus'

  - job_name: 'websocket-service'
    static_configs:
      - targets: ['websocket-service:8087']
    metrics_path: '/actuator/prometheus'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8088']
    metrics_path: '/actuator/prometheus'

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8089']
    metrics_path: '/actuator/prometheus'

  - job_name: 'activity-service'
    static_configs:
      - targets: ['activity-service:8090']
    metrics_path: '/actuator/prometheus'

  - job_name: 'location-service'
    static_configs:
      - targets: ['location-service:8091']
    metrics_path: '/actuator/prometheus'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']