apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: peraxis
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "peraxis_rules.yml"

    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway-service:8080']
        metrics_path: '/actuator/prometheus'
        scrape_interval: 30s

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8081']
        metrics_path: '/actuator/prometheus'
        scrape_interval: 30s

      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8082']
        metrics_path: '/actuator/prometheus'
        scrape_interval: 30s

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8083']
        metrics_path: '/actuator/prometheus'
        scrape_interval: 30s

      - job_name: 'ai-service'
        static_configs:
          - targets: ['ai-service:8084']
        metrics_path: '/actuator/prometheus'
        scrape_interval: 30s

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - peraxis
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

  peraxis_rules.yml: |
    groups:
    - name: peraxis.rules
      rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is above 500ms"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.instance }} has been down for more than 1 minute"