server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/peraxis_products

management:
  endpoints:
    web:
      exposure:
        include: health,info