server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis
      port: 6379
      password: peraxis123
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000,http://localhost:3001,http://localhost:3002"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: admin-service
          uri: http://admin-service:8085
          predicates:
            - Path=/api/admin/**
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/api/orders/**
        - id: ai-service
          uri: http://ai-service:8084
          predicates:
            - Path=/api/ai/**
        - id: payment-service
          uri: http://payment-service:8086
          predicates:
            - Path=/api/payments/**
        - id: websocket-service
          uri: http://websocket-service:8087
          predicates:
            - Path=/api/websocket/**
        - id: notification-service
          uri: http://notification-service:8088
          predicates:
            - Path=/api/notifications/**
        - id: search-service
          uri: http://search-service:8089
          predicates:
            - Path=/api/search/**
        - id: activity-service
          uri: http://activity-service:8090
          predicates:
            - Path=/api/activity/**
        - id: location-service
          uri: http://location-service:8091
          predicates:
            - Path=/api/location/**
        - id: admin-websocket
          uri: ws://admin-service:8085
          predicates:
            - Path=/ws/admin/**
        - id: websocket-connection
          uri: ws://websocket-service:8087
          predicates:
            - Path=/ws/**

jwt:
  secret: ${JWT_SECRET:peraxis-super-secret-jwt-key-change-in-production}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
