server:
  port: 8085

spring:
  application:
    name: admin-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:peraxis_admin}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:peraxis123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers