server:
  port: 8089

spring:
  application:
    name: search-service
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  elasticsearch:
    uris: http://localhost:9200

management:
  endpoints:
    web:
      exposure:
        include: health,info